# Generated by Django 6.0.4 on 2026-04-25 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('segmento', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DimProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(unique=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('precio_base', models.IntegerField()),
                ('proveedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DimTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FactVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta_origen', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dimcanal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dimcliente')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dimtiempo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.dimproducto')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'fecha'], name='core_factve_cliente_cca6ee_idx'), models.Index(fields=['canal', 'fecha'], name='core_factve_canal_i_fa3e0a_idx'), models.Index(fields=['producto', 'fecha'], name='core_factve_product_881732_idx')],
            },
        ),
    ]
