# Generated by Django 6.0.4 on 2026-07-02 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dimtiempo_calendario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='factventas',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.dimtienda'),
        ),
        migrations.AddIndex(
            model_name='factventas',
            index=models.Index(fields=['tienda', 'fecha'], name='core_factve_tienda__73809a_idx'),
        ),
    ]
